kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
featureGates:
  "EventedPLEG": false
networking:
  disableDefaultCNI: true

nodes:
 - role: control-plane
   image: gchr.io/mikezappa87/kni-demo:latest
 - role: worker
   image: gchr.io/mikezappa87/kni-demo:latest
