version: "3"

tasks:
  init-repos:
    desc: Initialize required repos (i.e. src/)
    cmds:
      - ./scripts/init_repos.sh
    #env:
      #uncomment if you want to pull whole repo (e.g. for development)
      #GIT_OPTION: ""
    aliases: [01-init]
  build:
    desc: Build required components
    cmds:
      - ./scripts/build.sh
    aliases: [02-build]
  setup:
    desc: Setup kind cluster and replace binaries
    cmds:
      - ./scripts/setup-flannel.sh
    aliases: [03-setup]
  setup-backwards:
    desc: Setup kind cluster and runs network-runtime/network plugins side by side
    cmds:
      - ./scripts/setup-backwards.sh
    aliases: [03-setup-backwards]
  setup-backwards-multus:
    desc: Setup kind cluster and runs network-runtime/network plugins side by side
    cmds:
      - ./scripts/setup-backwards-multus.sh
    aliases: [03-setup-backwards]
  setup-cilium:
    desc: Setup kind cluster and runs network-runtime/cilium side by side
    cmds:
      - ./scripts/setup-cilium.sh
    aliases: [03-setup-cilum]
  cleanup:
    desc: Cleanup kind cluster
    cmds:
      - ./scripts/cleanup.sh
  purge:
    desc: Delete src and bin
    cmds:
      - rm -rf ./bin || true
      - rm -rf ./src || true
  backwards:
    cmds:
      - ./scripts/setup-backwards.sh