version: "3"

tasks:
  init-repos:
    desc: Initialize required repos (i.e. src/)
    cmds:
      - ./scripts/init_repos.sh
    env:
      #uncomment if you want to pull whole repo (e.g. for development)
      #GIT_OPTION: ""
    aliases: [01-init]
  build:
    desc: Build required components
    cmds:
      - ./scripts/build.sh
    aliases: [02-build]
  setup:
    desc: Setup kind cluster and replace binaries
    cmds:
      - ./scripts/setup.sh
    aliases: [03-setup]
  cleanup:
    desc: Cleanup kind cluster
    cmds:
      - ./scripts/cleanup.sh
